# Generated by Django 4.1.4 on 2023-03-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Meme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("low_res", models.ImageField(upload_to="memes/meme/low_res")),
                ("high_res", models.ImageField(upload_to="memes/meme/high_res")),
                ("bottom_text", models.CharField(blank=True, max_length=200)),
                ("top_text", models.CharField(blank=True, max_length=200)),
                ("private", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="MemeTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("low_res", models.ImageField(upload_to="memes/template/low_res")),
                ("high_res", models.ImageField(upload_to="memes/template/high_res")),
            ],
        ),
    ]
